version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hcfakeapi_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: hcfakeapi_web
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FLASK_ENV: ${FLASK_ENV}
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
    depends_on:
      - db
    command: python run.py

volumes:
  pgdata:
